### ISSUE TITLE
🐞 [BUG]: Reported UX issues with Twitter Aggregation

### ISSUE THREAD

**Issue by alexbfree** [hestiaAI/hestialabs-experiences#1099]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Current Behavior

Paul has provided a video identifying a number of issues with user experience in the Twitter Aggregation experience:

> Hi all
> Aggregation was such a usability minefield that I recorded a video to show why. 
> 
> https://us06web.zoom.us/rec/share/qz2a1MSKLZsuCWiR1rDHnHKMXi0E2J0WBdSoDmBahfu2CenyiY-gbTxudVg4SSCK.i368WMx_arcnDA4g?startTime=1665697502000
>
> Passcode: *8.wKZ?3
> 
> Paul

This is additional and distinct from https://github.com/hestiaAI/clients/issues/55 but a similar kind of task

## Tasks for this ticket:

- [ ] review the video and write down the issues identified
- [ ] create tickets where needed and put them to the appropriate place on the board
- [ ] close up this ticket

### Expected Behavior

(to be documented from watching the video)

### Steps to Reproduce

1. Go to Digipower Academy Twitter Aggregate Experience
2. Review issues identified in the video

### Data Sources

(Assuming Sample data is OK - contact Paul if not)

### Web Sites

digipower.academy

### Browser

Firefox

### Operating System

Windows

**Comment by alexbfree** [comment]
The following issues were mentioned in the video:

- Advertising overview (last month) is blank from Paul's data
- In Aggregate, others couldn’t upload their data (is this the overwriting issue that valentin already fixed?)
- Paul wants to be able to select secret key without showing secret keys's folder
- Target criteria tab lists some data but empty graphs and doesn’t allow exploration
- advertising overview looks different than in individual view (is this because just 1 month was uploaded)
- Issues with not having permission/view to use share tab in participant experience (Yann mentioned this - need to clarify)

**Comment by valentinoli** [comment]
> * @valentinoli can you comment on whether multiple people uploading to bubbles is now fixed, i believe you were working on this?

Yes, it's fixed

**Comment by alexbfree** [comment]
Close by agreement including Paul at team meeting
