### ISSUE TITLE
Allow graphs written in d3.js

### ISSUE THREAD

**Issue by andreaskundig** [hestiaAI/hestialabs-experiences#136]
François is running into vega's limitations, for example when he wants a graph where you can drill down into options and would need some kind of navigation between choices.

# Tasks
- [x] Allow importing js files in manifest
- [x] Adapt configuration to indicate if a graph is in vega or d3
- [x] create a vue component that works with d3 
  - [ ] make sure that the graph adapts it's size to the enclosing html element

**Comment by valentinoli** [comment]
> Allow importing js files in manifest

Then we should convert the manifests to js files and not json. Originally I wanted to have them as JS files but then the requirement was that people configuring the experiences would not need any programming expertise. But the learning curve is very flat between the two formats for the configs and arguably JS files would be cleaner.

Example config in both formats

JSON
```json
{
  "title": "My experience",
  "multiple": true
}

```

JS
```js
export default {
  title: 'My experience',
  multiple: true
}
```
