### ISSUE TITLE
Check the format of CSV files when importing them

### ISSUE THREAD

**Issue by fquellec** [hestiaAI/hestialabs-experiences#145]
When we import a CSV file in TrackerControl experiment, for example, there is no type and format checking. An user could import any CSV file and the data will be passed to the visualisation component without verification.

# Tasks
- [ ] Allow type and format checking in the csv parser
- [ ] Display an error message when the format is not good
- [ ] Disable the process button if the format is not respected

For TrackerControl we expect (for now) a csv file formated as follow:
|uid|daddr|time|Tracker|Category|Package|App|
|---|---|---|---|---|---|---|
|Number|String|Timestamp|String|String|String|String|

This could be part of the general pipeline refactoring #147
