### ISSUE TITLE
Tools for defining new experiences and sharing data

### ISSUE THREAD

**Issue by andreaskundig** [hestiaAI/hestialabs-experiences#571]
An animator external to hestia should be able to set up a workshop based on experiences with the least possible help from hestia. The help from hestia should involve as little coding as possible.

The participants should be able to share data with the animator. The workshop should be able to share data with hestia.

# Configurable experiences
The animator uses the default experience to upload the files he wants to analyze.
- is he creating several experiences in his workshop ?

The default experience allows him to select data inside a json, click on a node and see it displayed as a table.
We will also need to
- display csv data when clicking on the file explorer
- display data as graph. We need some default graphs (bar chart, pie) and probably a way to specify what data goes where
- create a new tab from the graph chosen in the file explorer
- define the data that's exported in the consent form
- export the whole experience as json
- send the json to us by email using netlify forms

# Sharing data
- see if we can leverage webrtc for this

**Comment by andreaskundig** [comment]
TODO: take the following into consideration:
![PO-presentation-bubble-semantics-filter-2022-03-11](https://user-images.githubusercontent.com/899160/157839570-a42f604e-d326-458b-a43a-629a7f0de693.png)

**Comment by Amustache** [comment]
I started to formally compile our models [here](https://github.com/hestiaAI/lore/tree/master/knowledge/Models%20and%20abstractions). Feel free to complete.

As a reminder, the aim of the `lore` repository is to be a knowledge database that helps to have coherence between all projects.

**Comment by Amustache** [comment]
Okay, in there I will try to formalize a pipeline for the "data model" creation

# Big picture: data semantics and data model
## Definitions
- **Data model**: a list of relations between endpoints and semantic. Basically, given a JSON file with data from a specific, known source, the data model helps to _describe_ the data with semantic, i.e., "what each endpoint is" (e.g., "this is a date", or "this is a channel description").
- **Unknown data** := Data for which a data model does not exist yet, i.e., the data cannot be described.
- **Known data** := Data for which a data model exists, i.e., we can describe (part of) that data.

In both cases of data (unknown and known), the data contains specific data (e.g., a specific ID, a specific name, ...) - the difference is in the lack of description of this data.

## Model
_This is linked to OP's "1.c "Data Models""_
An example of what a model should contain could be the following:

| File name | Field name | Endpoint | Type | Description |
|---|---|---|---|---|
| `account-creation-ip.js` | `accountId` | `account_creation_ip.accountCreationIp.accountId` | Integer | Unique account ID for that user. |

It is very important to allow as many users as possible to benefit from the description of the data. Thus, the semantics should contain at least a high-level textual description of the endpoint (i.e., so that non-tech-savvy users can still understand), and a low-level formal description of the endpoint (i.e., so that a script can exploit the data).

Eventually, an example of the type of data might be useful to add directly into the model, but this is up for discussion.

An example of what a model should look like could be the following:
```json
{
  "fileName": "account-creation-ip.js",
  "filePath": "account-creation-ip.js",
  "fileFormat": "application/javascript",
  "description": "What IP was used to create that account.",
  "@graph": [
    {
      "@type": "Integer",
      "fieldName": "accountId",
      "unique": "True",
      "fieldPath": "accountCreationIp/accountId",
      "description": "Unique account ID for that user."
    },
  ]
},
```

Of course, **these are examples**, and the exact premises shall be worked on and iterated upon, again and again.

## Pipelines
There are two cases of use of the pipeline: the case of someone wanting to describe (new) models, and the case of someone wanting to use a model.

```mermaid
  graph TD;
      Data_source-->Unknown_data;
      Data_source-->Known_data;
      Unknown_data-->Create_new_model;
      Known_data-->Enhance_existing_model;
      Create_new_model-->Model;
      Enhance_existing_model-->Model;
      Model-->Use_model;
      Known_data-->Use_model;
      Use_model-->Analysis;
      Use_model-->Visualisation;
      Use_model-->Research;
      Use_model-->...;
```

In both cases, the idea is to allow the model to be augmented as the data is described. Ideally, the end user (i.e. the person who wants to use the data) also has the possibility to complete or amend a model with new elements.

Basically, what is wanted is the following:
```mermaid
  graph TD;
      I-->II;
      II-->II;
      II-->III;
      III-->II;
```

### I. Creating model from unknown data
```mermaid
  graph TD;
      Unknown_data-->JSON_format;
      JSON_format-->JSON_LD;
      JSON_LD-->Model;
```

1. **Parser**: First, an unknown source is converted into a JSON format to make it easier to use. In most cases, this conversion will be trivial, but difficulties may exist.
2. **Description**: The JSON file is supplemented with semantics (=descriptions), using the JSON-LD format.
3. **Anonymisation**: We remove all the specific data, to keep only the description, and obtain in the end a JSON-LD agnostic file.

### II. Enhancing model from known data
```mermaid
  graph TD;
      Known_data-->JSON_format;
      JSON_format-->JSON_LD;
      JSON_LD-->Model;
```

The operations are identical, except that the description will have to augment/correct the existing model.

### III. Using a model
_This may be linked to OP's "2. Visualizations"_

Once a template is ready, it should be able to be used in many different cases. The advantage of having a standardised format is that it will be easy to transcribe the information from the template to other existing elements (e.g., `pandas`, ...). However, it is worth bearing in mind that you will need to create appropriate conversion tools, depending on your needs.

**Comment by Amustache** [comment]
# Constraints and steps
## Step 0: Getting the data
_This step is facultative but can be a good entry point._

The first part of obtaining data to exploit is to provide easy access to it. There are websites, such as [JustGetMyData](https://justgetmydata.com/), which already reference methods for retrieving data, but a dedicated portal allowing the user to query the available data may be interesting. We can add more information, like for instance from [JustWhatsTheData](https://justwhatsthedata.github.io/), so that the portal is complete.

An example of a prototype can be found on the following picture:

![image](https://user-images.githubusercontent.com/5108539/158820394-d3ae061f-cf5e-4a46-b872-6ea1e880540b.png)

From this portal, we can propose to people, after obtaining their data, to analyse them, locally, and potentially share their results with a collective or more.

## Step 1: Loading tool for data tagging
_The following graph is broken and needs repair._

```mermaid
stateDiagram-v2
st=>start: Receiving data
lc=>operation: Load converter
cj=>operation: Convert to JSon
lm=>operation: Load model
cm=>operation: Create model
nc=>condition: Need converting to JSon?
ec=>condition: Existing converter?
em=>condition: Existing model?
pr=>end: Redirect to Issues/PR/form
td=>end: Tagging data

st->nc
nc(yes)->ec
ec(no)->pr
ec(yes)->lc->cj->em
nc(no)->em
em(yes)->lm->td
em(no)->cm->td
​```

## Step 2: Loading model and data
For this step, it will be necessary to check at the level of the needs to have conversions of the model according to the needs.

**Comment by pdehaye** [comment]
> @pdehaye : "Le but n'est pas forcément que la personne qui a la data puisse tout faire sans programmation, c'est davantage que la personne qui a la data puisse trouver quelqu'un avec un ensemble de compétences (programmation) pour arriver au but qu'il souhaite."

A noter que ce quelqu'un peut etre Hestia.ai mais dans un autre mode: non plus comme orchestrateur mais comme utilisateur du service de l'orchestrateur pour receptionner des datas brutes et a partir de la les structurer. Cela montre a mon avis que nous devrions nous a l'interne d'abord nous structurer nous-memes autour des APIs qu'on voudrait externaliser.

**Comment by Amustache** [comment]
Discussion du jour :

**Subtasks**
- [ ] Raw export to SQL/DB : @wilderino & @Amustache 
- [ ] SQL/DB to visu : @fquellec 
- [ ] SQL/DB to elsewhere : @andreaskundig 

The idea is to have something on a really high specification level, that will generate Django models, that can be used to generate whatever afterwards + can be used with JS.

Sidenote, maybe pin that issue, as it is kind of a "master thread" for the next steps.

**Comment by Amustache** [comment]
Discussion avec @andreaskundig @wilderino @Amustache 

## Méthodes de filtrage
### Méthode 1 (Filtre défini par défaut en amont)

- Filtrage défini par un modèle JSON-LD, à partir de ça ça détermine les données, et on les affiche - la visualisation n'aide que à montrer ce que l'on partage.
- Le format de données résultante (e.g., un json, une table, ...) va être configuré en donnant le fichier JSON-LD, et à l'export ça donne ce que l'on veut.
- A la fin on pourra juste exporter les données fournies par le bloc.

**Ici, l'idée est d'appliquer un filtre _avant_ d'utiliser les données et de les transformer en table.**

### Méthode 2 (Application des filtres à la création de la base de données)

- Pour pouvoir appliquer le filtrage plus évolué de @wilderino, avec une version interactive, il faut que l'on puisse passer du modèle de data à une ou plusieurs tables SQL dans la base de données (qui est le point de départ de @wilderino).
- Il faudrait pouvoir les définir de la même manière.
- Dans Expériences, le filtrage des données serait une nouvelle pipeline SQL, avec une visualisation derrière.

**Ici, l'idée est d'appliquer un filtre _après_ avoir créé la table globale dans expérience.**

## Étapes (mix'd)
1. Définir le datamodel qui définit les données à utiliser.
1. Passer du datamodel à une table.
1. Par-dessus, avoir un filtre à définir.

**Comment by Amustache** [comment]
I forgot to reference this here, but https://github.com/hestiaAI/tools/blob/main/ApplePrivacyReport/mockup.ipynb may be relevant to that discussion.
