### ISSUE TITLE
bubbles: filtering and sharing data

### ISSUE THREAD

**Issue by andreaskundig** [hestiaAI/hestialabs-experiences#649]
Deadline for new features is June 13th, when we have a workshop.
There's a first workshop on May 17th where we tell them (how to get their data ?).

They will be using data from google (GPS, wifi, activity), and maybe also from Trackercontrol.

# bubble workflow overview

Workshop participants have access to a bubble, which looks somewhat like experiences.hestialabs.org

Participants:
- enter a password to access the bubble (the same for every participant)
- choose an experience those available for that specific bubble
- upload their data
- filter out time periods, geographic regions, apps, about which they don't want to share data
- answer some bubble specific questions in the consent form
- choose what visualizations to share
- share their data with the workhop moderator by clicking one button

The workshop moderator has access to his own bubble, which looks somewhat like experiences.hestialabs.org
- uploads his private key to access the bubble, (and decrypt the data shared by participants)
- chooses which shared participant files to analyze (simpler: use all uploaded files at first)
- compares/aggregates them with visualizations

There could be additional bubbles for researchers or journalists, that would have each its own consent form, with which the moderator could share additionally filtered data.

# Tasks
- [x] #661
- [x] #658
- [x] #708 
- [x] #709
- [x] #710
- [x] #659 [See bubble-server's README](https://github.com/hestiaAI/bubble-server#the-rest-api)
- [x] write the bubble-server: hestiaAI/bubble-server#1
- [x] deploy the bubble-server: hestiaAI/bubble-server#2
- [x] #660
- [x] hestiaAI/bubble-server#11
- [x] hestiaAI/bubble-server#12
- [x] ensure uploaded file name is unique (hash input files) 
- [x] upload participant files to aggregator bubble

**Comment by pdehaye** [comment]
Comments:
* For the filters, already for the TL workshop, it would be good to see the geolocation filtering as applicable to other apps than just google (within the extent possible for generic geolocation approach), and before the consenting step. In other words, if one of the participants has a willingness to retrieve their data from transport company X and wants to show it, it would be good if they can filter their data a bit first ("here is my FAIRTIQ data for last month's weekdays")
* You talk of a "destination consent form", and seem to imply that the consent decision comes first, and then the destination decision. For as long as we have just one destination, or we stand up new hosted sites for each destination, that will be true. But I don't think we will want to keep that for very long. We really shouldn't. Some destinations will be more trusted than others ("Hestia engineers for debugging") and should enable sharing more. This is not too relevant for the workshop but relevant on other parallel projects (where we expect timelines to be longer). 
* watch out with using filenames. sometimes different SAR outputs have same filenames for everyone, sometimes they have participant names (which bubble drive host might not want to see!), sometimes different datestamps for the same person, etc.
